### PR TITLE
Fix running a simple nitro node

### LINKED ISSUE #26: Fix the testnode with flag `--init` only

### LINKED ISSUE #206: nitro-testnode: Ensure the espresso variant works with `--simple`
This will simplify the upgrade test because we only need to run a single nitro node.

### PR DESCRIPTION
**Pull request by ImJeremyHe**
Closes https://github.com/EspressoSystems/nitro-espresso-integration/issues/206
Closes #26 

### This PR:
- Run a simple nitro node sucessfully. Use a more elegant way to keep the config compatible with upstream
- Add a smoke test for it
- Add a .gitignore file

This is helpful when doing the migration test.

### Key places to review:
- test-node.bash
- rollupcreator/Dockerfile

### How to test this PR
```
./test-node.bash --init--force --simple
```

### CODE REVIEW

**Comment by sveitser** [comment]
@ImJeremyHe I'm on mobile, so difficult to review. Does this support writing an espresso config for the simple node? We also need this for the upgrade test.

**Comment by sveitser** [comment]
I see it should be supported. Do you know if it works?

**Review by sveitser — APPROVED** [review]

**Comment by ImJeremyHe** [comment]
@sveitser 
Do you mean running the test node with --simple and --espresso --latest-espresso-image?

**Comment by sveitser** [comment]
Yes

**Pull request merged**
